;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="UI.Frontend.Widget.StartScreen",DevComment="")
+GameplayTagRedirects=(OldTagName="UI.Widget.Frontend.PressAnyKeyScreen",NewTagName="UI.Frontend.Widget.PressAnyKeyScreen")
+GameplayTagRedirects=(OldTagName="UI.Widget.Frontend.MainMenuScreen",NewTagName="UI.Frontend.Widget.MainMenuScreen")
+GameplayTagRedirects=(OldTagName="UI.Widget.Frontend.OptionsScreen",NewTagName="UI.Frontend.Widget.OptionsScreen")
+GameplayTagRedirects=(OldTagName="UI.Widget.Frontend.ConfirmScreen",NewTagName="UI.Frontend.Widget.ConfirmScreen")
+GameplayTagRedirects=(OldTagName="UI.Widget.Frontend.StartScreen",NewTagName="UI.Frontend.Widget.StartScreen")
+GameplayTagRedirects=(OldTagName="UI.Image.Frontend.TestImage",NewTagName="UI.Frontend.Image.TestImage")

